// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/awa/go-iap/playstore (interfaces: IABProduct,IABProductV2,IABSubscription,IABSubscriptionV2,IABMonetization,IABOrder)
//
// Generated by this command:
//
//	mockgen -destination=mocks/playstore.go -package=mocks github.com/awa/go-iap/playstore IABProduct,IABProductV2,IABSubscription,IABSubscriptionV2,IABMonetization,IABOrder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	androidpublisher "google.golang.org/api/androidpublisher/v3"
)

// MockIABProduct is a mock of IABProduct interface.
type MockIABProduct struct {
	ctrl     *gomock.Controller
	recorder *MockIABProductMockRecorder
	isgomock struct{}
}

// MockIABProductMockRecorder is the mock recorder for MockIABProduct.
type MockIABProductMockRecorder struct {
	mock *MockIABProduct
}

// NewMockIABProduct creates a new mock instance.
func NewMockIABProduct(ctrl *gomock.Controller) *MockIABProduct {
	mock := &MockIABProduct{ctrl: ctrl}
	mock.recorder = &MockIABProductMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIABProduct) EXPECT() *MockIABProductMockRecorder {
	return m.recorder
}

// AcknowledgeProduct mocks base method.
func (m *MockIABProduct) AcknowledgeProduct(arg0 context.Context, arg1, arg2, arg3, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcknowledgeProduct", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcknowledgeProduct indicates an expected call of AcknowledgeProduct.
func (mr *MockIABProductMockRecorder) AcknowledgeProduct(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcknowledgeProduct", reflect.TypeOf((*MockIABProduct)(nil).AcknowledgeProduct), arg0, arg1, arg2, arg3, arg4)
}

// ConsumeProduct mocks base method.
func (m *MockIABProduct) ConsumeProduct(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeProduct", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConsumeProduct indicates an expected call of ConsumeProduct.
func (mr *MockIABProductMockRecorder) ConsumeProduct(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeProduct", reflect.TypeOf((*MockIABProduct)(nil).ConsumeProduct), arg0, arg1, arg2, arg3)
}

// VerifyProduct mocks base method.
func (m *MockIABProduct) VerifyProduct(arg0 context.Context, arg1, arg2, arg3 string) (*androidpublisher.ProductPurchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyProduct", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*androidpublisher.ProductPurchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyProduct indicates an expected call of VerifyProduct.
func (mr *MockIABProductMockRecorder) VerifyProduct(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyProduct", reflect.TypeOf((*MockIABProduct)(nil).VerifyProduct), arg0, arg1, arg2, arg3)
}

// MockIABProductV2 is a mock of IABProductV2 interface.
type MockIABProductV2 struct {
	ctrl     *gomock.Controller
	recorder *MockIABProductV2MockRecorder
	isgomock struct{}
}

// MockIABProductV2MockRecorder is the mock recorder for MockIABProductV2.
type MockIABProductV2MockRecorder struct {
	mock *MockIABProductV2
}

// NewMockIABProductV2 creates a new mock instance.
func NewMockIABProductV2(ctrl *gomock.Controller) *MockIABProductV2 {
	mock := &MockIABProductV2{ctrl: ctrl}
	mock.recorder = &MockIABProductV2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIABProductV2) EXPECT() *MockIABProductV2MockRecorder {
	return m.recorder
}

// VerifyProductV2 mocks base method.
func (m *MockIABProductV2) VerifyProductV2(arg0 context.Context, arg1, arg2 string) (*androidpublisher.ProductPurchaseV2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyProductV2", arg0, arg1, arg2)
	ret0, _ := ret[0].(*androidpublisher.ProductPurchaseV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyProductV2 indicates an expected call of VerifyProductV2.
func (mr *MockIABProductV2MockRecorder) VerifyProductV2(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyProductV2", reflect.TypeOf((*MockIABProductV2)(nil).VerifyProductV2), arg0, arg1, arg2)
}

// MockIABSubscription is a mock of IABSubscription interface.
type MockIABSubscription struct {
	ctrl     *gomock.Controller
	recorder *MockIABSubscriptionMockRecorder
	isgomock struct{}
}

// MockIABSubscriptionMockRecorder is the mock recorder for MockIABSubscription.
type MockIABSubscriptionMockRecorder struct {
	mock *MockIABSubscription
}

// NewMockIABSubscription creates a new mock instance.
func NewMockIABSubscription(ctrl *gomock.Controller) *MockIABSubscription {
	mock := &MockIABSubscription{ctrl: ctrl}
	mock.recorder = &MockIABSubscriptionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIABSubscription) EXPECT() *MockIABSubscriptionMockRecorder {
	return m.recorder
}

// AcknowledgeSubscription mocks base method.
func (m *MockIABSubscription) AcknowledgeSubscription(arg0 context.Context, arg1, arg2, arg3 string, arg4 *androidpublisher.SubscriptionPurchasesAcknowledgeRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcknowledgeSubscription", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcknowledgeSubscription indicates an expected call of AcknowledgeSubscription.
func (mr *MockIABSubscriptionMockRecorder) AcknowledgeSubscription(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcknowledgeSubscription", reflect.TypeOf((*MockIABSubscription)(nil).AcknowledgeSubscription), arg0, arg1, arg2, arg3, arg4)
}

// CancelSubscription mocks base method.
func (m *MockIABSubscription) CancelSubscription(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelSubscription", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelSubscription indicates an expected call of CancelSubscription.
func (mr *MockIABSubscriptionMockRecorder) CancelSubscription(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSubscription", reflect.TypeOf((*MockIABSubscription)(nil).CancelSubscription), arg0, arg1, arg2, arg3)
}

// DeferSubscription mocks base method.
func (m *MockIABSubscription) DeferSubscription(arg0 context.Context, arg1, arg2, arg3 string, arg4 *androidpublisher.SubscriptionPurchasesDeferRequest) (*androidpublisher.SubscriptionPurchasesDeferResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeferSubscription", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*androidpublisher.SubscriptionPurchasesDeferResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeferSubscription indicates an expected call of DeferSubscription.
func (mr *MockIABSubscriptionMockRecorder) DeferSubscription(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeferSubscription", reflect.TypeOf((*MockIABSubscription)(nil).DeferSubscription), arg0, arg1, arg2, arg3, arg4)
}

// MockIABSubscriptionV2 is a mock of IABSubscriptionV2 interface.
type MockIABSubscriptionV2 struct {
	ctrl     *gomock.Controller
	recorder *MockIABSubscriptionV2MockRecorder
	isgomock struct{}
}

// MockIABSubscriptionV2MockRecorder is the mock recorder for MockIABSubscriptionV2.
type MockIABSubscriptionV2MockRecorder struct {
	mock *MockIABSubscriptionV2
}

// NewMockIABSubscriptionV2 creates a new mock instance.
func NewMockIABSubscriptionV2(ctrl *gomock.Controller) *MockIABSubscriptionV2 {
	mock := &MockIABSubscriptionV2{ctrl: ctrl}
	mock.recorder = &MockIABSubscriptionV2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIABSubscriptionV2) EXPECT() *MockIABSubscriptionV2MockRecorder {
	return m.recorder
}

// RevokeSubscriptionV2 mocks base method.
func (m *MockIABSubscriptionV2) RevokeSubscriptionV2(arg0 context.Context, arg1, arg2 string, arg3 *androidpublisher.RevokeSubscriptionPurchaseRequest) (*androidpublisher.RevokeSubscriptionPurchaseResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSubscriptionV2", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*androidpublisher.RevokeSubscriptionPurchaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeSubscriptionV2 indicates an expected call of RevokeSubscriptionV2.
func (mr *MockIABSubscriptionV2MockRecorder) RevokeSubscriptionV2(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSubscriptionV2", reflect.TypeOf((*MockIABSubscriptionV2)(nil).RevokeSubscriptionV2), arg0, arg1, arg2, arg3)
}

// VerifySubscriptionV2 mocks base method.
func (m *MockIABSubscriptionV2) VerifySubscriptionV2(arg0 context.Context, arg1, arg2 string) (*androidpublisher.SubscriptionPurchaseV2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifySubscriptionV2", arg0, arg1, arg2)
	ret0, _ := ret[0].(*androidpublisher.SubscriptionPurchaseV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifySubscriptionV2 indicates an expected call of VerifySubscriptionV2.
func (mr *MockIABSubscriptionV2MockRecorder) VerifySubscriptionV2(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifySubscriptionV2", reflect.TypeOf((*MockIABSubscriptionV2)(nil).VerifySubscriptionV2), arg0, arg1, arg2)
}

// MockIABMonetization is a mock of IABMonetization interface.
type MockIABMonetization struct {
	ctrl     *gomock.Controller
	recorder *MockIABMonetizationMockRecorder
	isgomock struct{}
}

// MockIABMonetizationMockRecorder is the mock recorder for MockIABMonetization.
type MockIABMonetizationMockRecorder struct {
	mock *MockIABMonetization
}

// NewMockIABMonetization creates a new mock instance.
func NewMockIABMonetization(ctrl *gomock.Controller) *MockIABMonetization {
	mock := &MockIABMonetization{ctrl: ctrl}
	mock.recorder = &MockIABMonetizationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIABMonetization) EXPECT() *MockIABMonetizationMockRecorder {
	return m.recorder
}

// GetSubscription mocks base method.
func (m *MockIABMonetization) GetSubscription(ctx context.Context, packageName, productID string) (*androidpublisher.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscription", ctx, packageName, productID)
	ret0, _ := ret[0].(*androidpublisher.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockIABMonetizationMockRecorder) GetSubscription(ctx, packageName, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscription", reflect.TypeOf((*MockIABMonetization)(nil).GetSubscription), ctx, packageName, productID)
}

// GetSubscriptionOffer mocks base method.
func (m *MockIABMonetization) GetSubscriptionOffer(arg0 context.Context, arg1, arg2, arg3, arg4 string) (*androidpublisher.SubscriptionOffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionOffer", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*androidpublisher.SubscriptionOffer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionOffer indicates an expected call of GetSubscriptionOffer.
func (mr *MockIABMonetizationMockRecorder) GetSubscriptionOffer(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionOffer", reflect.TypeOf((*MockIABMonetization)(nil).GetSubscriptionOffer), arg0, arg1, arg2, arg3, arg4)
}

// MockIABOrder is a mock of IABOrder interface.
type MockIABOrder struct {
	ctrl     *gomock.Controller
	recorder *MockIABOrderMockRecorder
	isgomock struct{}
}

// MockIABOrderMockRecorder is the mock recorder for MockIABOrder.
type MockIABOrderMockRecorder struct {
	mock *MockIABOrder
}

// NewMockIABOrder creates a new mock instance.
func NewMockIABOrder(ctrl *gomock.Controller) *MockIABOrder {
	mock := &MockIABOrder{ctrl: ctrl}
	mock.recorder = &MockIABOrderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIABOrder) EXPECT() *MockIABOrderMockRecorder {
	return m.recorder
}

// BatchGetOrder mocks base method.
func (m *MockIABOrder) BatchGetOrder(ctx context.Context, packageName string, orderIds ...string) (*androidpublisher.BatchGetOrdersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, packageName}
	for _, a := range orderIds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchGetOrder", varargs...)
	ret0, _ := ret[0].(*androidpublisher.BatchGetOrdersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetOrder indicates an expected call of BatchGetOrder.
func (mr *MockIABOrderMockRecorder) BatchGetOrder(ctx, packageName any, orderIds ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, packageName}, orderIds...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetOrder", reflect.TypeOf((*MockIABOrder)(nil).BatchGetOrder), varargs...)
}

// GetOrder mocks base method.
func (m *MockIABOrder) GetOrder(ctx context.Context, packageName, orderId string) (*androidpublisher.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, packageName, orderId)
	ret0, _ := ret[0].(*androidpublisher.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockIABOrderMockRecorder) GetOrder(ctx, packageName, orderId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockIABOrder)(nil).GetOrder), ctx, packageName, orderId)
}

// Refund mocks base method.
func (m *MockIABOrder) Refund(ctx context.Context, packageName, orderId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refund", ctx, packageName, orderId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refund indicates an expected call of Refund.
func (mr *MockIABOrderMockRecorder) Refund(ctx, packageName, orderId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refund", reflect.TypeOf((*MockIABOrder)(nil).Refund), ctx, packageName, orderId)
}

// ReviewRefund mocks base method.
func (m *MockIABOrder) ReviewRefund(ctx context.Context, packageName, orderId string, req *androidpublisher.OrdersReviewRefundRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReviewRefund", ctx, packageName, orderId, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReviewRefund indicates an expected call of ReviewRefund.
func (mr *MockIABOrderMockRecorder) ReviewRefund(ctx, packageName, orderId, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReviewRefund", reflect.TypeOf((*MockIABOrder)(nil).ReviewRefund), ctx, packageName, orderId, req)
}
