name: Bump version and Create release.

on:
  workflow_dispatch:

jobs:
  tagging-release:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@af99e60ce8132224b8e6ebab5023449fe256ed46 # v7.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
          tag_prefix: "v"

      - name: Get latest release
        if: steps.tag_version.outputs.new_tag != ''
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        id: latest_release
        with:
          result-encoding: string
          retries: 3
          script: |
            const res = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            return res.data.tag_name;

      - name: Generate release note and Create release
        if: steps.tag_version.outputs.new_tag != ''
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          retries: 3
          script: |
            const note = await github.rest.repos.generateReleaseNotes({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ steps.tag_version.outputs.new_tag }}",
              previous_tag_name: "${{ steps.latest_release.outputs.result }}"
            })

            const res = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ steps.tag_version.outputs.new_tag }}",
              name: note.data.name,
              body: note.data.body
            })
            return res.data;